"""empty message

Revision ID: 85bfcb260ad6
Revises: de9b6f945093
Create Date: 2025-05-21 13:37:46.008011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85bfcb260ad6'
down_revision = 'de9b6f945093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('area_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('siembra', sa.String(length=20), nullable=False),
    sa.Column('area', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('area_id'),
    sa.UniqueConstraint('siembra')
    )
    op.create_table('bloques',
    sa.Column('bloque_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('bloque', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('bloque_id'),
    sa.UniqueConstraint('bloque')
    )
    op.create_table('camas',
    sa.Column('cama_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cama', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('cama_id'),
    sa.UniqueConstraint('cama')
    )
    op.create_table('causas_perdida',
    sa.Column('causa_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('es_predefinida', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('causa_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('colores',
    sa.Column('color_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('color_abrev', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('color_id'),
    sa.UniqueConstraint('color'),
    sa.UniqueConstraint('color_abrev')
    )
    op.create_table('densidades',
    sa.Column('densidad_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('densidad', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('densidad_id'),
    sa.UniqueConstraint('densidad')
    )
    op.create_table('documentos',
    sa.Column('doc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('documento', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('doc_id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('flores',
    sa.Column('flor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flor', sa.String(length=10), nullable=False),
    sa.Column('flor_abrev', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('flor_id'),
    sa.UniqueConstraint('flor'),
    sa.UniqueConstraint('flor_abrev')
    )
    op.create_table('lados',
    sa.Column('lado_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lado', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('lado_id'),
    sa.UniqueConstraint('lado')
    )
    op.create_table('permisos',
    sa.Column('permiso_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('permiso_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('roles',
    sa.Column('rol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('rol_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('bloques_camas_lado',
    sa.Column('bloque_cama_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bloque_id', sa.SmallInteger(), nullable=True),
    sa.Column('cama_id', sa.Integer(), nullable=True),
    sa.Column('lado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bloque_id'], ['bloques.bloque_id'], ),
    sa.ForeignKeyConstraint(['cama_id'], ['camas.cama_id'], ),
    sa.ForeignKeyConstraint(['lado_id'], ['lados.lado_id'], ),
    sa.PrimaryKeyConstraint('bloque_cama_id'),
    sa.UniqueConstraint('bloque_id', 'cama_id', 'lado_id')
    )
    op.create_table('flor_color',
    sa.Column('flor_color_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flor_id', sa.Integer(), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['colores.color_id'], ),
    sa.ForeignKeyConstraint(['flor_id'], ['flores.flor_id'], ),
    sa.PrimaryKeyConstraint('flor_color_id'),
    sa.UniqueConstraint('flor_id', 'color_id')
    )
    op.create_table('roles_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.permiso_id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.rol_id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('tipos_labor',
    sa.Column('tipo_labor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('flor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flor_id'], ['flores.flor_id'], ),
    sa.PrimaryKeyConstraint('tipo_labor_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_1', sa.String(length=20), nullable=False),
    sa.Column('nombre_2', sa.String(length=20), nullable=True),
    sa.Column('apellido_1', sa.String(length=20), nullable=False),
    sa.Column('apellido_2', sa.String(length=20), nullable=True),
    sa.Column('cargo', sa.String(length=30), nullable=False),
    sa.Column('num_doc', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.doc_id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.rol_id'], ),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('variedades',
    sa.Column('variedad_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variedad', sa.String(length=100), nullable=False),
    sa.Column('flor_color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flor_color_id'], ['flor_color.flor_color_id'], ),
    sa.PrimaryKeyConstraint('variedad_id')
    )
    op.create_table('siembras',
    sa.Column('siembra_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bloque_cama_id', sa.Integer(), nullable=False),
    sa.Column('variedad_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('densidad_id', sa.Integer(), nullable=False),
    sa.Column('fecha_siembra', sa.Date(), nullable=False),
    sa.Column('fecha_inicio_corte', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('Activa', 'Finalizada'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin_corte', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.ForeignKeyConstraint(['bloque_cama_id'], ['bloques_camas_lado.bloque_cama_id'], ),
    sa.ForeignKeyConstraint(['densidad_id'], ['densidades.densidad_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.ForeignKeyConstraint(['variedad_id'], ['variedades.variedad_id'], ),
    sa.PrimaryKeyConstraint('siembra_id')
    )
    op.create_table('cortes',
    sa.Column('corte_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('siembra_id', sa.Integer(), nullable=False),
    sa.Column('num_corte', sa.Integer(), nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=False),
    sa.Column('cantidad_tallos', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['siembra_id'], ['siembras.siembra_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('corte_id'),
    sa.UniqueConstraint('siembra_id', 'num_corte', name='siembra_corte_unique')
    )
    op.create_table('labores_culturales',
    sa.Column('labor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('siembra_id', sa.Integer(), nullable=False),
    sa.Column('tipo_labor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_labor', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['siembra_id'], ['siembras.siembra_id'], ),
    sa.ForeignKeyConstraint(['tipo_labor_id'], ['tipos_labor.tipo_labor_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('labor_id')
    )
    op.create_table('perdidas',
    sa.Column('perdida_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('siembra_id', sa.Integer(), nullable=False),
    sa.Column('causa_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_perdida', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['causa_id'], ['causas_perdida.causa_id'], ),
    sa.ForeignKeyConstraint(['siembra_id'], ['siembras.siembra_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ),
    sa.PrimaryKeyConstraint('perdida_id')
    )
    with op.batch_alter_table('vista_produccion_acumulada', schema=None) as batch_op:
        batch_op.drop_column('total_perdidas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vista_produccion_acumulada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_perdidas', mysql.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('perdidas')
    op.drop_table('labores_culturales')
    op.drop_table('cortes')
    op.drop_table('siembras')
    op.drop_table('variedades')
    op.drop_table('usuarios')
    op.drop_table('tipos_labor')
    op.drop_table('roles_permisos')
    op.drop_table('flor_color')
    op.drop_table('bloques_camas_lado')
    op.drop_table('roles')
    op.drop_table('permisos')
    op.drop_table('lados')
    op.drop_table('flores')
    op.drop_table('documentos')
    op.drop_table('densidades')
    op.drop_table('colores')
    op.drop_table('causas_perdida')
    op.drop_table('camas')
    op.drop_table('bloques')
    op.drop_table('areas')
    # ### end Alembic commands ###
