"""añadir columna fecha_perdida a tabla perdidas

Revision ID: de9b6f945093
Revises: 55a354d74c84
Create Date: 2025-05-19 11:10:57.265498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de9b6f945093'
down_revision = '55a354d74c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminando todas las operaciones excepto añadir la columna fecha_perdida
    
    with op.batch_alter_table('perdidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_perdida', sa.Date(), nullable=False, server_default=sa.text("'2000-01-01'")))
        
        # Comentando las operaciones de claves foráneas por si ya existen o son problemáticas
        # Si necesitas estas operaciones, puedes descomentar las siguientes líneas
        # batch_op.drop_constraint('fk_perdida_causa', type_='foreignkey')
        # batch_op.create_foreign_key(None, 'causas_perdida', ['causa_id'], ['causa_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perdidas', schema=None) as batch_op:
        # Comentando operaciones de claves foráneas
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key('fk_perdida_causa', 'causas', ['causa_id'], ['causa_id'])
        
        # Solo mantener la eliminación de la columna
        batch_op.drop_column('fecha_perdida')

    # ### end Alembic commands ###