"""Eliminar campo fecha_perdida de perdidas

Revision ID: e0a8fcdd3553
Revises: 82426420c8f7
Create Date: 2023-11-08 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0a8fcdd3553'
down_revision = '82426420c8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perdidas', 'fecha_perdida')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perdidas', sa.Column('fecha_perdida', sa.DATE(), nullable=True))
    # ### end Alembic commands ###